plugins:
  - jekyll-titles-from-headings

title: SEC (Software Engineering Club)
description: Learning Git
theme: minima
markdown: kramdown

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true